### ISSUE TITLE
Cost calulation

### ISSUE THREAD

**Issue by Deapper** [jneilliii/OctoPrint-TPLinkSmartplug#124]
Hi thanks for the great plugin.

Not trying to blow your project out as I'm sure you have RL to deal with. But it would be great if you could enter your cost for KWH and have a readout for it... Just a thought, its great as it is. All the best lol

**Comment by kylane** [comment]
Agree with this and would be happy to donate to get it to happen!

**Comment by jneilliii** [comment]
How would you guys propose it to be displayed, in the sidebar or as part of the tab, possibly in the graph (this could be  difficult to implement).

**Comment by kylane** [comment]
> How would you guys propose it to be displayed, in the sidebar or as part of the tab, possibly in the graph (this could be difficult to implement).

I think the sidebar tab would be fine - maybe even a historical list of prints with their associated costs?

**Comment by jneilliii** [comment]
Eventually some of this is going to get integrated into [OctoPrint-PrintJobHistory](https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1) plugin but I'll definitely try to update the sidebar at least with some simple math that multiplies a number by the current `Power` value.

**Comment by kylane** [comment]
Eager to see it implemented @jneilliii - Ill have to polish up on my python to offer any pull requests.

**Comment by jneilliii** [comment]
This actually can be achieved fairly easily on the javascript knockout observable side using a computed observable and a reference to it in the jinja template.

**Comment by kylane** [comment]
Great news

**Comment by jneilliii** [comment]
So I'm not sure how helpful this is going to be. Since there is no snapshot of start and end time for the print job in the current implementation.  You could reset the plug's stored data and start from scratch for each print, then at the end take note of the final cost value.  Or the value at start of print and at end of print and take the difference.  I think what you're really looking for is the [PrintJobHistory](https://github.com/OllisGit/OctoPrint-PrintJobHistory) plugin and once it integrates power consumption it would give you that data for billing that you are looking for.

![image](https://user-images.githubusercontent.com/5249455/71426440-6a9f2600-2677-11ea-8a38-da853474c4ff.png)

![image](https://user-images.githubusercontent.com/5249455/71426457-d08bad80-2677-11ea-965c-b045d59e1235.png)

**Comment by jneilliii** [comment]
So my latest dev branch has integrated this stuff now.  You can install using the URL below in plugin manager.  If you don't mind testing and give some feedback that would be great.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.18.zip

**Comment by kylane** [comment]
> So my latest dev branch has integrated this stuff now. You can install using the URL below in plugin manager. If you don't mind testing and give some feedback that would be great.
> 
> https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.18.zip

Awesome - will test tonight.

**Comment by kylane** [comment]
Apologies havent had a chance to test - had issues with my printer - just waiting on new metal hotend and dual Z kit.
