### ISSUE TITLE
[Feature Request]: Support for KL430 Kasa LED Strips?

### ISSUE THREAD

**Issue by noverman** [jneilliii/OctoPrint-TPLinkSmartplug#217]
Would it be possible to add support for the TP Link Kasa LED light strips KL430? 

Wanting to be able to turn off the LED when the printer is idle similar to the way the smart plug works as well. 

Thank you!

**Comment by jneilliii** [comment]
It might make more sense for this to be controlled with my [TPLinkSmartBulb](https://github.com/jneilliii/OctoPrint-TPLinkSmartBulb) plugin rather than this one since it's light related. I do not however know if those use the same communication protocol or not as the bulb. You could try that plugin just to see if it works and if not open a feature request there instead.
