### ISSUE TITLE
Turnoff Plug After Print Complete?

### ISSUE THREAD

**Issue by wizbowes** [jneilliii/OctoPrint-TPLinkSmartplug#24]
Hi,

Love this plugin.  No issues, but I was wondering if would be possible to configure this so that the plug turns off after printing is completed.  Either via a timer or when the head gets below a certain temp.

Thanks for the plugin

wizbowes

**Comment by ttocsneb** [comment]
One thing that I have done with my setup was to add this to the end of the 'After print job completes' section of 'GCODE Scripts' in the system settings

    G4 P300000; Wait 5 minutes to let the Hot end cool
    M81; The TPLink plugin will interpret this, and turn off the smart plug

**Comment by jneilliii** [comment]
That was going to be my suggestion as well. However, with the latest
version you need to issue the command as M81 ip. Example documented on
readme in the gcode section.

On Oct 25, 2017 8:43 PM, "Benjamin Jacobs" <notifications@github.com> wrote:

One thing that I have done with my setup was to add this to the end of the
'After print job completes' section of 'GCODE Scripts' in the system
settings

G4 P300000; Wait 5 minutes to let the Hot end cool
M81; The TPLink plugin will interpret this, and turn off the smart plug

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/24#issuecomment-339515843>,
or mute the thread

**Comment by jneilliii** [comment]
This is possible via gcode commands, allowing it to be set in octoprint's settings to be applied for all prints or in am individual basis via end gcode in your slicer application.
